model_list:
  - model_name: nvidia-glm-5.3-flash
    litellm_params:
      model: nvidia_nim/z-ai/glm-5-3-flash
      api_base: os.environ/NVIDIA_NIM_API_BASE
      api_key: os.environ/NVIDIA_NIM_API_KEY
  - model_name: nvidia-kimi-k3
    litellm_params:
      model: nvidia_nim/moonshotai/kimi-k3
      api_base: os.environ/NVIDIA_NIM_API_BASE
      api_key: os.environ/NVIDIA_NIM_API_KEY
  - model_name: nvidia-glm-5.3
    litellm_params:
      model: nvidia_nim/z-ai/glm-5-3
      api_base: os.environ/NVIDIA_NIM_API_BASE
      api_key: os.environ/NVIDIA_NIM_API_KEY
  - model_name: nvidia-deepseek-v4-flash-0731
    litellm_params:
      model: nvidia_nim/deepseek-ai/deepseek-v4-flash-0731
      api_base: os.environ/NVIDIA_NIM_API_BASE
      api_key: os.environ/NVIDIA_NIM_API_KEY
  - model_name: nvidia-nemotron-3-ultra
    litellm_params:
      model: nvidia_nim/nvidia/nemotron-3-ultra-550b-a55b
      api_base: os.environ/NVIDIA_NIM_API_BASE
      api_key: os.environ/NVIDIA_NIM_API_KEY
  - model_name: nvidia-muse-glimmer-30b
    litellm_params:
      model: nvidia_nim/meta/muse-glimmer-30b
      api_base: os.environ/NVIDIA_NIM_API_BASE
      api_key: os.environ/NVIDIA_NIM_API_KEY
  - model_name: nvidia-nemotron-omni-30b
    litellm_params:
      model: nvidia_nim/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning
      api_base: os.environ/NVIDIA_NIM_API_BASE
      api_key: os.environ/NVIDIA_NIM_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
